on: [push]

jobs:

  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: >
        sudo apt-get install -qq -y
        asciidoctor
        ruby-asciidoctor-pdf ruby-rouge
    - name: Prepare results directory
      run: mkdir out
    - name: Build guide.html
      run: >
        asciidoctor
        --quiet
        --backend html
        --destination-dir out
        --attribute webfonts!
        --attribute stylesheet=style.css
        guide.adoc
    - name: Build guide.pdf
      run: >-
        asciidoctor
        --quiet
        --require asciidoctor-pdf
        --backend pdf
        --destination-dir out
        guide.adoc
    - name: Upload artefacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: out/

  deploy-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build-docs
    runs-on: ubuntu-latest
    name: Deploy to GH Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy materials to GH Pages
      uses: actions/deploy-pages@v4
